cache:          90j34hfobuw4onihbgof4nfwj4

highlighter:    rouge
markdown:       kramdown
kramdown:
  parse_block_html: true
permalink:      ./:title
paginate:       10
postLimit:      10
paginate_path: "/news/page:num/"
name:           CLC Striders
description:    "Cheltenham Ladies College Striders Running Club"
slogan:         "CLC Striders Running Club"
author:         CLC Strider
url:            https://striders.thechels.uk
themeColor:     3e9b00
copyright:      "CLC Striders"
twitter:        https://twitter.com/CLCStriders
facebook:       https://www.facebook.com/CLCStriders/
strava:         https://www.strava.com/clubs/clc-striders
instagram:      https://instagram.com/CLCStriders
encoding:       UTF-8
future:         false
toc:            true
exclude:        ["README"]
sass:
  style:        compressed
plugins:
  - jekyll-feed
  - jekyll-paginate
