highlighter:    rouge
permalink:      ./:title
name:           CLC Striders
description:    "Cheltenahm Running Club"
author:         Strider
url:            https://striders.thechels.uk
copyright:      "CLC Striders"
encoding:       UTF-8
future:         false
exclude:        ["README"]
sass:
  style:        compressed
gems:
  - jekyll-feed
