###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################

cache:          20200211_go_live_v2
markdown:       kramdown
highlighter:    rouge
kramdown:
  parse_block_html: true
permalink:      ./news/:year-:month-:day-:title
postLimit:      15
name:           CLC Striders
description:    "Welcome to CLC Striders, an inclusive and competitive running club based in Cheltenham. Affiliated to England Athletics."
title:          "CLC Striders"
subtitle:       "Running Club"
defaultAnnouncements: "Welcome to CLC Striders - One of Cheltenham's largest running clubs - based at Cheltenham Ladies College"
author:         CLC Strider
url:            https://clcstriders-runningclub.co.uk
themeColor:     3e9b00
copyright:      "CLC Striders"
twitter:        https://twitter.com/CLCStriders
facebook:       https://www.facebook.com/CLCStriders/
strava:         https://www.strava.com/clubs/clc-striders
instagram:      https://instagram.com/CLCStriders
CLCHFC:         https://fitness.cheltladiescollege.org/
mapUrl_CLC:     https://www.google.co.uk/maps/place/Cheltenham,+Gloucestershire+GL50+2NX/@51.8996855,-2.0905991,17.26z/data=!4m2!3m1!1s0x48711b750b7cf72f:0x18adca3553c78bca?hl=en
mapUrl_POW:     https://www.google.com/maps/place/Prince+of+Wales+Stadium/@51.9110056,-2.0818891,17z/data=!3m1!4b1!4m5!3m4!1s0x48711b844ca41ec7:0x85ff62e695d5800d!8m2!3d51.9110056!4d-2.0797004
ga:             G-SZT11FK24G
encoding:       UTF-8
future:         false
toc:            true
slider:         true
announcements:  true
collections:
  announcements:
  sliderImages:
  
exclude:        ["README"]
sass:
  style:        compressed
plugins:        [ jekyll-feed, jekyll-paginate, jekll-sitemap]
