cache:          kjbtv87g756t
markdown:       kramdown
highlighter:    rouge
kramdown:
  parse_block_html: true
permalink:      ./:title
postLimit:      10
name:           CLC Striders
description:    "Cheltenham Ladies College Striders Running Club"
slogan:         "CLC Striders Running Club"
author:         CLC Strider
url:            https://striders.thechels.uk
themeColor:     3e9b00
copyright:      "CLC Striders"
twitter:        https://twitter.com/CLCStriders
facebook:       https://www.facebook.com/CLCStriders/
strava:         https://www.strava.com/clubs/clc-striders
instagram:      https://instagram.com/CLCStriders
encoding:       UTF-8
future:         false
toc:            true
exclude:        ["README"]
sass:
  style:        compressed
plugins:        [ jekyll-feed, jekyll-paginate, jekll-sitemap]
