highlighter:    rouge
markdown:       kramdown
permalink:      ./:title
paginate:       10
postLimit:      25
paginate_path: "/news/page:num/"
name:           CLC Striders
description:    "Cheltenham Running Club"
slogan:         "Cheltenham Running Club"
author:         CLC Strider
url:            https://striders.thechels.uk
cache:          hkgjyvtu
themeColor:     3e9b00
copyright:      "CLC Striders"
twitter:        https://twitter.com/CLCStriders
facebook:       https://www.facebook.com/CLCStriders/
strava:         https://www.strava.com/clubs/clc-striders
instagram:      https://instagram.com/CLCStriders
encoding:       UTF-8
future:         false
exclude:        ["README"]
sass:
  style:        compressed
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-github-metadata

collections:
 category:
 output: true
 
 defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
