highlighter:    rouge
permalink:      ./:title
name:           CLC Striders
description:    "Cheltenham Running Club"
slogan:         "Cheltenham Running Club"
author:         CLC Strider
url:            https://striders.thechels.uk
cache:          i3hroaewhngluiejwanfkweogbenFJLKBVJKXJFG
themeColor:     3e9b00
copyright:      "CLC Striders"
twitter:        https://twitter.com/CLCStriders
facebook:       https://www.facebook.com/CLCStriders/
strava:         https://www.strava.com/clubs/clc-striders
instagram:      https://instagram.com/CLCStriders
encoding:       UTF-8
future:         true
exclude:        ["README"]
sass:
  style:        compressed
gems:
  - jekyll-feed
