cache:          hjvkcx
markdown:       kramdown
highlighter:    rouge
kramdown:
  parse_block_html: true
permalink:      ./news/:year-:month-:day-:title
postLimit:      15
name:           CLC Striders
description:    "Cheltenham Ladies College Striders Running Club"
slogan:         "CLC Striders Running Club"
defaultAnnouncements: "Welcome to CLC Striders - One of Cheltenham's largest running clubs - based at Cheltenham Ladies College"
author:         CLC Strider
url:            https://striders.thechels.uk
themeColor:     3e9b00
copyright:      "CLC Striders"
twitter:        https://twitter.com/CLCStriders
facebook:       https://www.facebook.com/CLCStriders/
strava:         https://www.strava.com/clubs/clc-striders
instagram:      https://instagram.com/CLCStriders
ga:             G-SZT11FK24G
encoding:       UTF-8
future:         false
toc:            true
slider:         true
announcements:  true
collections:
  announcements:
  sliderImages:
exclude:        ["README"]
sass:
  style:        compressed
plugins:        [ jekyll-feed, jekyll-paginate, jekll-sitemap]
