contact_links:
  - name: Need help?
    url: https://github.com/CLCStriders/striders/wiki
    about: Please read the wiki before creating an issue
  - name: Contributing
    url: https://github.com/CLCStriders/striders/blob/master/.github/CONTRIBUTING.md
    about: Please read about contributing.